FROM node:22-alpine

WORKDIR /usr/src/app

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm install
# dependance pour sequelize et les cookies
RUN npm install pg pg-hstore sequelize cookie-parser

# Installer nodemon globalement
RUN npm install -g nodemon

# Copier la configuration de nodemon
COPY nodemon.json ./

EXPOSE 3000

# Utiliser nodemon avec la configuration
CMD ["nodemon", "--legacy-watch"]
